// Online ticket checkout — the one place a ticket can be sold on the web.
//
// What this replaces: both online paths created confirmed, scannable tickets
// without taking any money. The guest path inserted rows from an edge function
// with no card step at all; the signed-in path inserted them straight from the
// browser, which also meant the *browser* decided the price. There was no
// Square code on either path — nothing to switch from sandbox to live.
//
// The order of operations is the fix, and it is the whole design:
//
//     price on the server  ->  write the order as pending  ->  charge Square
//                          ->  confirm the tickets  ->  deliver them
//
// Nothing scannable exists until the money moves. A decline leaves failed rows
// and sends no email. A crash between charge and confirm leaves a pending order
// with a Square payment id on it — recoverable, and never a free ticket.
//
// Both the guest and the signed-in checkout call this. Neither inserts tickets
// any more; the RLS policy that allowed a customer to insert their own ticket
// is dropped in the accompanying migration, so this is the only route left.
//
// Card data never touches this function or this server. The browser hands the
// card to Square's own iframe and sends us a single-use token, which is all
// `source_id` below ever is. (PCI SAQ A-EP.)

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { json, preflight } from '../_shared/http.ts';
import {
  createPayment,
  loadSquareConfig,
  publishableConfig,
  squareErrorMessage,
} from '../_shared/square.ts';
import { PricingError, priceTicketOrder, type TicketDescriptor } from '../_shared/pricing.ts';
import { deliverConfirmation } from '../_shared/deliver.ts';
import {
  EMAIL_RE,
  authenticatedUser,
  contactForUser,
  findOrCreateBuyer,
  readContact,
  type BuyerContact,
} from '../_shared/buyers.ts';

// Deno globals
declare const Deno: any;

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const ANON_KEY = Deno.env.get('SUPABASE_ANON_KEY')!;

const MAX_TICKETS_PER_SHOWING = 4;

/**
 * How long a pending order holds its seats.
 *
 * A pending row normally lives for the seconds a card charge takes. But if the
 * isolate dies between the insert and the charge, the row stays pending
 * forever — and without an expiry that abandoned row would keep a seat
 * un-sellable and count against the buyer's four-ticket limit for good. After
 * this window a pending row is treated as abandoned: it holds nothing.
 */
const PENDING_HOLD_MS = 15 * 60 * 1000;
const HELD_STATUSES = ['confirmed', 'pending'];

function isHeld(row: { status: string; purchased_at: string }): boolean {
  if (row.status === 'confirmed') return true;
  return Date.now() - new Date(row.purchased_at).getTime() < PENDING_HOLD_MS;
}

Deno.serve(async (req: Request) => {
  if (req.method === 'OPTIONS') return preflight();

  let body: Record<string, any>;
  try {
    body = await req.json();
  } catch {
    return json({ error: 'Invalid JSON body' }, 400);
  }

  const square = loadSquareConfig();

  // The browser needs the publishable ids before it can render the card form.
  if (body.action === 'get_config') {
    if (!square.ok) return json({ error: square.error }, 500);
    return json(publishableConfig(square.config));
  }

  if (body.action && body.action !== 'create_purchase') {
    return json({ error: `Unknown action: ${body.action}` }, 400);
  }

  const admin = createClient(SUPABASE_URL, SERVICE_ROLE_KEY);

  // -------------------------------------------------------------------------
  // Request shape
  // -------------------------------------------------------------------------
  const showingId = String(body.showing_id ?? '').trim();
  const descriptors: TicketDescriptor[] = Array.isArray(body.tickets) ? body.tickets : [];
  const paymentMethod = body.payment_method === 'film_pass' ? 'film_pass' : 'card';
  const sourceId = typeof body.source_id === 'string' ? body.source_id : '';
  const passId = typeof body.pass_id === 'string' ? body.pass_id : '';

  if (!showingId) return json({ error: 'Showing is required' }, 400);
  if (descriptors.length === 0) return json({ error: 'Select at least one ticket' }, 400);
  if (descriptors.length > MAX_TICKETS_PER_SHOWING) {
    return json({ error: `Maximum ${MAX_TICKETS_PER_SHOWING} tickets per purchase` }, 400);
  }
  if (paymentMethod === 'film_pass' && !passId) {
    return json({ error: 'Select a film pass to redeem' }, 400);
  }
  // A card source is required only once we know there is money to charge. A
  // free ($0) showing has no card step at all, so it is validated after pricing
  // rather than here — see the post-pricing guard below.

  // One key per checkout attempt, generated by the browser and resent on retry.
  const idempotencyKey = normaliseKey(body.idempotency_key);

  // -------------------------------------------------------------------------
  // Who is buying
  // -------------------------------------------------------------------------
  const signedIn = await authenticatedUser(createClient, req);
  let contact: BuyerContact = readContact(body);
  let userId: string;
  // Whether this purchase silently created an account. The confirmation email
  // uses it to decide whether to offer a password-set link, so a returning
  // customer is not told an account was made for them.
  let accountCreated = false;

  if (signedIn) {
    userId = signedIn.id;
    contact = await contactForUser(admin, userId, contact);
  } else {
    if (!contact.name) return json({ error: 'Name is required' }, 400);
    if (!contact.email && !contact.phone) {
      return json({ error: 'Email or phone is required so we can send your tickets' }, 400);
    }
    if (contact.email && !EMAIL_RE.test(contact.email)) {
      return json({ error: 'Invalid email format' }, 400);
    }
    if (paymentMethod === 'film_pass') {
      // A pass belongs to an account; redeeming one requires being in it.
      return json({ error: 'Sign in to redeem a film pass' }, 401);
    }
    try {
      const buyer = await findOrCreateBuyer(admin, contact);
      userId = buyer.userId;
      accountCreated = buyer.created;
    } catch (err) {
      console.error('[ticket-checkout] buyer resolution failed', err);
      return json({ error: err instanceof Error ? err.message : 'Could not create account' }, 500);
    }
  }

  // A resubmitted attempt returns the order it already made. Matching on the
  // buyer as well as the key means a guessed key reveals nothing.
  const replay = await findExistingOrder(admin, idempotencyKey, userId);
  if (replay) return json(replay);

  // -------------------------------------------------------------------------
  // Price it — from the database, never from the request
  // -------------------------------------------------------------------------
  let order;
  try {
    order = await priceTicketOrder(
      admin,
      showingId,
      descriptors,
      paymentMethod === 'film_pass' ? 'none' : 'online',
    );
  } catch (err) {
    if (err instanceof PricingError) return json({ error: err.message }, 400);
    console.error('[ticket-checkout] pricing failed', err);
    return json({ error: 'Could not price this order' }, 500);
  }

  // A paid card order must carry a Square token; a free ($0) showing must not
  // need one. (Square rejects a $0 charge outright — "below the minimum" — which
  // is why free tickets skip Square entirely, below.)
  if (paymentMethod === 'card' && order.amountCents > 0 && !sourceId) {
    return json({ error: 'Missing payment source' }, 400);
  }

  // -------------------------------------------------------------------------
  // Availability and limits
  // -------------------------------------------------------------------------
  const seatIds = order.tickets.map((t) => t.seat_id).filter((id): id is string => !!id);

  if (seatIds.length > 0) {
    if (new Set(seatIds).size !== seatIds.length) {
      return json({ error: 'The same seat was selected twice' }, 400);
    }
    const { data: taken } = await admin
      .from('tickets')
      .select('seat_id, status, purchased_at')
      .eq('showing_id', showingId)
      .in('seat_id', seatIds)
      .in('status', HELD_STATUSES);
    if ((taken || []).filter(isHeld).length > 0) {
      return json({ error: 'Someone just took one of those seats. Please pick again.' }, 409);
    }
  } else if (order.showing.requires_seat_selection) {
    return json({ error: 'This showing requires seat selection' }, 400);
  } else {
    const { data: soldRows } = await admin
      .from('tickets')
      .select('id, status, purchased_at')
      .eq('showing_id', showingId)
      .in('status', HELD_STATUSES);
    const sold = (soldRows || []).filter(isHeld).length;
    if (sold + order.tickets.length > order.showing.total_seats) {
      return json({ error: 'Not enough tickets left for this showing' }, 409);
    }
  }

  const { data: ownRows } = await admin
    .from('tickets')
    .select('id, status, purchased_at')
    .eq('showing_id', showingId)
    .eq('user_id', userId)
    .in('status', HELD_STATUSES);

  const alreadyHeld = (ownRows || []).filter(isHeld).length;
  if (alreadyHeld + order.tickets.length > MAX_TICKETS_PER_SHOWING) {
    return json(
      {
        error: `Ticket limit reached. You already have ${alreadyHeld} ticket(s) for this showing.`,
      },
      400,
    );
  }

  // -------------------------------------------------------------------------
  // Film pass: verify the pass covers it *before* anything is written
  // -------------------------------------------------------------------------
  let pass: any = null;
  if (paymentMethod === 'film_pass') {
    const { data } = await admin
      .from('user_film_passes')
      .select('id, user_id, remaining_balance, expires_at, status')
      .eq('id', passId)
      .maybeSingle();

    // Ownership is checked here, on the server. The redemption RPC does not
    // check it, which is why the client may no longer call that RPC at all.
    if (!data || data.user_id !== userId) return json({ error: 'Film pass not found' }, 404);
    if (data.status !== 'active') return json({ error: 'That film pass is not active' }, 400);
    if (data.expires_at && new Date(data.expires_at) < new Date()) {
      return json({ error: 'That film pass has expired' }, 400);
    }
    // Passes are tax-inclusive: the deduction is the pre-tax subtotal.
    if (Number(data.remaining_balance) < order.subtotal) {
      return json(
        {
          error: `Insufficient pass balance. Need $${order.subtotal.toFixed(2)}, have $${Number(
            data.remaining_balance,
          ).toFixed(2)}.`,
        },
        400,
      );
    }
    pass = data;
  }

  // -------------------------------------------------------------------------
  // Write the order as pending
  // -------------------------------------------------------------------------
  const orderToken = crypto.randomUUID();
  const ticketRows = order.tickets.map((t, i) => ({
    user_id: userId,
    showing_id: showingId,
    seat_id: t.seat_id,
    tier_id: t.tier_id,
    price: t.price,
    tax_rate: 0.06,
    tax_amount: t.tax_amount,
    total_price: t.total_price,
    // The surcharge belongs to the order, not to a seat; it rides on the first
    // row so refunds can recover it without an orders table.
    processing_fee: i === 0 ? order.processingFee : 0,
    qr_code: crypto.randomUUID(),
    order_token: orderToken,
    status: 'pending',
    payment_method: paymentMethod === 'film_pass' ? 'film_pass' : 'online',
    checkout_idempotency_key: idempotencyKey,
  }));

  const { data: created, error: insertErr } = await admin
    .from('tickets')
    .insert(ticketRows)
    .select('id, qr_code, price, total_price, seat_id, tier_id');

  if (insertErr || !created || created.length === 0) {
    console.error('[ticket-checkout] pending insert failed', insertErr);
    return json({ error: 'Could not start this purchase. Please try again.' }, 500);
  }

  const ticketIds = created.map((t: any) => t.id);
  const failOrder = async (reason: string) => {
    await admin
      .from('tickets')
      .update({ status: 'failed', payment_error: reason.slice(0, 500) })
      .in('id', ticketIds);
  };

  // -------------------------------------------------------------------------
  // Take the money
  // -------------------------------------------------------------------------
  let receiptUrl: string | null = null;
  let paymentId: string | null = null;

  if (paymentMethod === 'film_pass') {
    // Prepaid — no card, no Square. The amount deducted is the server's
    // per-ticket price; previously the browser supplied it.
    try {
      for (const ticket of created) {
        const { error: redeemErr } = await admin.rpc('redeem_film_pass', {
          p_pass_id: pass.id,
          p_ticket_id: ticket.id,
          p_amount: Number(ticket.price),
        });
        if (redeemErr) throw new Error(redeemErr.message);
      }
    } catch (err) {
      // Balance and expiry were checked above, so reaching here means a
      // concurrent redemption drained the pass mid-order. Deductions already
      // recorded stay — they have redemption rows against real tickets, and
      // those tickets are about to be marked failed, which is the state an
      // admin can see and correct.
      const reason = err instanceof Error ? err.message : 'Film pass redemption failed';
      console.error('[ticket-checkout] redemption failed', err);
      await failOrder(reason);
      return json({ error: reason }, 400);
    }
  } else if (order.amountCents === 0) {
    // Free showing — no money moves, so Square is skipped entirely (it rejects
    // a $0 charge). The tickets are still confirmed below, so the seat is held,
    // counts toward capacity, and scans at the door. paymentId/receiptUrl stay
    // null, exactly as they would for a comp.
  } else {
    if (!square.ok) {
      await failOrder(square.error);
      return json({ error: 'Payments are not configured. Please contact the box office.' }, 500);
    }

    try {
      const result = await createPayment(square.config, {
        sourceId,
        amountCents: order.amountCents,
        idempotencyKey,
        referenceId: orderToken,
        note: `${order.productionTitle} — ${created.length} ticket(s)`,
        buyerEmail: contact.email,
      });

      if (!result.ok || !result.data?.payment) {
        const message = squareErrorMessage(result.data);
        console.error('[ticket-checkout] Square declined', JSON.stringify(result.data));
        await failOrder(message);
        return json({ error: message }, 400);
      }

      const payment = result.data.payment;
      if (payment.status && payment.status !== 'COMPLETED') {
        // Nothing scannable for a payment that has not actually completed.
        const message = `Payment did not complete (${payment.status}).`;
        await failOrder(message);
        return json({ error: message }, 400);
      }

      paymentId = payment.id ?? null;
      receiptUrl = payment.receipt_url ?? null;
    } catch (err) {
      const reason = err instanceof Error ? err.message : 'Payment failed';
      console.error('[ticket-checkout] payment threw', err);
      await failOrder(reason);
      return json({ error: 'Payment could not be processed. Your card was not charged.' }, 500);
    }
  }

  // -------------------------------------------------------------------------
  // Paid — now the tickets become real
  // -------------------------------------------------------------------------
  const { error: confirmErr } = await admin
    .from('tickets')
    .update({
      status: 'confirmed',
      square_payment_id: paymentId,
      square_receipt_url: receiptUrl,
      payment_error: null,
    })
    .in('id', ticketIds);

  if (confirmErr) {
    // The card *was* charged. Say so plainly and leave the rows pending with
    // the payment id attached, rather than pretending the sale failed.
    console.error('[ticket-checkout] confirm failed after charge', confirmErr, { paymentId });
    return json(
      {
        error:
          'Your payment went through but we could not finish issuing the tickets. Please contact the box office — do not pay again.',
        square_payment_id: paymentId,
      },
      500,
    );
  }

  // -------------------------------------------------------------------------
  // Deliver — fire-and-forget, never able to fail a paid purchase
  // -------------------------------------------------------------------------
  // Called in-process, not by POSTing to send-ticket-confirmation. That HTTP
  // hop forwarded the service-role key as a bearer alongside the anon key in
  // `apikey`, and once Supabase rotated the injected keys to the
  // sb_publishable_/sb_secret_ format the gateway began refusing the pair
  // outright: 401 "Conflicting API keys". The request never reached the
  // sibling function, and since the dispatch is fire-and-forget nothing
  // surfaced -- the purchase succeeded, the card was charged, and no ticket
  // was ever sent. In-process has no gateway and no credential to forward.
  const delivery = deliverConfirmation(admin, orderToken, {
    email: contact.email || undefined,
    phone: contact.phone || undefined,
    name: contact.name || undefined,
    accountCreated,
  }).catch((e) => console.error('[ticket-checkout] confirmation dispatch failed', e));

  // waitUntil keeps the send alive past this response; a bare `void fetch` can
  // be killed when the isolate is torn down.
  // @ts-ignore — EdgeRuntime exists only in the Supabase edge runtime.
  if (typeof EdgeRuntime !== 'undefined' && EdgeRuntime?.waitUntil) {
    // @ts-ignore
    EdgeRuntime.waitUntil(delivery);
  }

  syncMailchimp(contact, order, created, showingId);

  return json({
    success: true,
    order_token: orderToken,
    user_id: userId,
    tickets: created,
    ticket_count: created.length,
    payment_method: paymentMethod,
    amount_cents: paymentMethod === 'film_pass' ? 0 : order.amountCents,
    subtotal: order.subtotal,
    tax: order.tax,
    processing_fee: order.processingFee,
    total: paymentMethod === 'film_pass' ? 0 : order.grandTotal,
    receipt_url: receiptUrl,
    square_payment_id: paymentId,
  });
});

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function normaliseKey(raw: unknown): string {
  const key = typeof raw === 'string' ? raw.trim() : '';
  // Square caps idempotency keys at 45 characters.
  return key.length >= 8 && key.length <= 45 ? key : crypto.randomUUID();
}

/** The order this key already created, if the buyer is retrying. */
async function findExistingOrder(admin: any, idempotencyKey: string, userId: string) {
  const { data } = await admin
    .from('tickets')
    .select('id, qr_code, price, total_price, seat_id, tier_id, order_token, status, square_payment_id, square_receipt_url')
    .eq('checkout_idempotency_key', idempotencyKey)
    .eq('user_id', userId);

  const rows = (data || []).filter((t: any) => t.status === 'confirmed');
  if (rows.length === 0) return null;

  return {
    success: true,
    replayed: true,
    order_token: rows[0].order_token,
    user_id: userId,
    tickets: rows,
    ticket_count: rows.length,
    receipt_url: rows[0].square_receipt_url ?? null,
    square_payment_id: rows[0].square_payment_id ?? null,
  };
}

/**
 * Marketing sync. Fire-and-forget by design: a Mailchimp outage must never
 * affect a completed purchase.
 */
function syncMailchimp(
  contact: BuyerContact,
  order: { productionTitle: string; productionCategory: string; subtotal: number },
  tickets: any[],
  showingId: string,
) {
  if (!contact.email) return;
  try {
    const [first, ...rest] = contact.name.split(/\s+/);
    void fetch(`${SUPABASE_URL}/functions/v1/mailchimp-subscribe`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', apikey: ANON_KEY },
      body: JSON.stringify({
        email: contact.email,
        first_name: first ?? '',
        last_name: rest.join(' '),
        tags: ['ticket-buyer'],
        source: 'ticket-checkout',
      }),
    }).catch(() => {});

    void fetch(`${SUPABASE_URL}/functions/v1/mailchimp-ecommerce`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        apikey: ANON_KEY,
        Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
      },
      body: JSON.stringify({
        email: contact.email,
        first_name: first ?? '',
        last_name: rest.join(' '),
        order: {
          id: `tickets:${tickets[0].id}`,
          total: tickets.reduce((s: number, t: any) => s + Number(t.total_price || 0), 0),
          lines: tickets.map((t: any) => ({
            id: t.id,
            product_id: showingId,
            product_title: order.productionTitle,
            quantity: 1,
            price: Number(t.total_price || 0),
            category: order.productionCategory,
          })),
        },
      }),
    }).catch(() => {});
  } catch (e) {
    console.warn('[ticket-checkout] mailchimp sync threw', e);
  }
}
