/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8f6c823b95e9d42d1235473163d53591)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	SUPABASE_URL: "https://rpqzrpboyhshdrfdwayk.supabase.co" | "https://vlmslygnimfbamrtwvyo.supabase.co";
	SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcXpycGJveWhzaGRyZmR3YXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzOTE2NzksImV4cCI6MjEwMTk2NzY3OX0.SlNsS4nZq1Nb6FH4JM0gAeQb5gQ9Qy22CNoolbJvlU0" | "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsbXNseWduaW1mYmFtcnR3dnlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM1MzYzNzUsImV4cCI6MjA5OTExMjM3NX0.qPBblAfE1PP5lMbXRtPid0wa_3J7urXOpRAosdAGtH4";
	SITE_URL: "https://kenworthy-ticketing-staging.mrtomfrank.workers.dev" | "https://kenworthy.org";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface StagingEnv {
		ASSETS: Fetcher;
		SUPABASE_URL: "https://rpqzrpboyhshdrfdwayk.supabase.co";
		SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwcXpycGJveWhzaGRyZmR3YXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzOTE2NzksImV4cCI6MjEwMTk2NzY3OX0.SlNsS4nZq1Nb6FH4JM0gAeQb5gQ9Qy22CNoolbJvlU0";
		SITE_URL: "https://kenworthy-ticketing-staging.mrtomfrank.workers.dev";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
