import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
};

/**
 * Inbound Mailchimp webhook. Public — verify_jwt=false.
 * Auth is a shared secret in the `?s=` query param, generated by
 * mailchimp-bootstrap and stored in app_config. Mailchimp does not sign
 * webhook bodies; this is the accepted pattern.
 *
 * Mailchimp GETs the URL first to validate; respond 200 to any GET.
 * On POST, forms come as application/x-www-form-urlencoded with fields like
 *   type=subscribe|unsubscribe|profile|upemail|cleaned
 *   data[email]=..., data[list_id]=..., data[new_email]=...
 *
 * ---------------------------------------------------------------------------
 * What this endpoint is allowed to change, and why it is so little
 * ---------------------------------------------------------------------------
 *
 * A query-string secret is a weaker credential than a signature, and it is the
 * strongest one available: Mailchimp will not sign a webhook body. A secret in
 * a URL is written to proxy logs, browser history and referrer headers in a way
 * a signature header never is, and — because there is no timestamp to bound —
 * a captured request can be replayed forever.
 *
 * So the credential is treated as one that may leak, and the blast radius is
 * kept to what a leak can survive. This endpoint sets `marketing_opt_in` and
 * nothing else.
 *
 * It used to do more. On `type=upemail` it took two addresses out of the
 * request body and rewrote `profiles.email` from one to the other, which is a
 * stranger changing the identity on an account. `profiles.email` is not
 * decorative: `invite-staff` resolves an invitation to an existing account by
 * looking it up there *first*, and `_shared/buyers.ts` matches a guest buyer to
 * an account the same way. Rewriting it desynchronises the profile from
 * `auth.users`, which is the actual source of truth for signing in, and leaves
 * both of those lookups pointing at the wrong person.
 *
 * Mailchimp is a mailing list. It does not get to decide who someone is here,
 * so the address rewrite is gone and an `upemail` now only ensures the old
 * address stops receiving marketing. Changing an account's email is a job for
 * the account holder, through auth.
 */

/**
 * Length-independent comparison, so a mismatch leaks no timing information.
 *
 * `!==` on a secret returns as soon as two characters differ, and the time that
 * takes is a function of how many leading characters were right. Over a network
 * with a database round trip in front of it that signal is deep in the noise —
 * but the fix is four lines and does not depend on that staying true.
 */
function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function readFormData(req: Request): Promise<Record<string, string>> {
  const ct = req.headers.get("content-type") || "";
  const out: Record<string, string> = {};
  if (ct.includes("application/json")) {
    const j = await req.json().catch(() => ({}));
    // Flatten data[email] etc for uniform access
    for (const [k, v] of Object.entries(j)) {
      if (typeof v === "object" && v !== null) {
        for (const [k2, v2] of Object.entries(v as Record<string, unknown>)) {
          out[`${k}[${k2}]`] = String(v2 ?? "");
        }
      } else out[k] = String(v ?? "");
    }
    return out;
  }
  const body = await req.text();
  const params = new URLSearchParams(body);
  for (const [k, v] of params.entries()) out[k] = v;
  return out;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });

  const url = new URL(req.url);
  const providedSecret = url.searchParams.get("s") || "";

  const admin = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );

  const { data: cfg } = await admin
    .from("app_config").select("value").eq("key", "mailchimp_webhook").maybeSingle();
  const expected = cfg?.value?.secret;
  if (!expected || providedSecret.length < 16 || !timingSafeEqual(providedSecret, expected)) {
    return new Response("forbidden", { status: 403, headers: corsHeaders });
  }

  // Mailchimp verification ping
  if (req.method === "GET") return new Response("ok", { status: 200, headers: corsHeaders });
  if (req.method !== "POST") return new Response("method not allowed", { status: 405, headers: corsHeaders });

  let form: Record<string, string> = {};
  try { form = await readFormData(req); } catch { return new Response("bad body", { status: 400, headers: corsHeaders }); }

  const type = form["type"];
  const email = (form["data[email]"] || "").toLowerCase().trim();

  try {
    if (type === "unsubscribe" || type === "cleaned") {
      if (email) {
        await admin.from("profiles").update({ marketing_opt_in: false }).eq("email", email);
      }
    } else if (type === "subscribe") {
      if (email) {
        await admin.from("profiles").update({ marketing_opt_in: true }).eq("email", email);
      }
    } else if (type === "upemail") {
      // The subscriber changed their address *in Mailchimp*. All that means
      // here is that the old address is no longer one we should market to —
      // see the header comment for why the account's own email is left alone.
      // The new address arrives with its own subscribe event if it is one of
      // ours.
      if (email) {
        await admin.from("profiles").update({ marketing_opt_in: false }).eq("email", email);
      }
    }
    // 'profile' updates are informational only
  } catch (e) {
    console.error("[mailchimp-webhook] update failed", e);
  }

  return new Response("ok", { status: 200, headers: corsHeaders });
});